Fix linking breakage in tests
libtool: link: /usr/local/bin/clang -DPIC -fPIC -I../../../../git/include -g -ggdb -Wall -Werror -Wdeclaration-after-statement -Wsign-compare -Wc++-compat -fno-omit-frame-pointer -O0 -D_REENTRANT -D_GNU_SOURCE -DXIO_CFLAG_EXTRA_CHECKS -DXIO_CFLAG_STAT_COUNTERS -DVERB_READ -DTEST_LAT -fsanitize=address,undefined -fno-omit-frame-pointer -Wno-address-of-packed-member -Wno-unused-function -o .libs/xio_read_lat xio_read_lat-xio_msg.o xio_read_lat-xio_perftest_client.o xio_read_lat-xio_perftest_server.o xio_read_lat-xio_perftest_parameters.o xio_read_lat-xio_perftest_communication.o xio_read_lat-xio_perftest.o xio_read_lat-get_clock.o  /home/arne/Projects/openvstorage/accelio/build/src/usr/.libs/libxio.so -lrdmacm -libverbs -lrt -lpthread -L../../../src/usr/ -lnuma
xio_read_lat-xio_msg.o: In function `xio_buf_free':
/home/arne/Projects/openvstorage/accelio/build/benchmarks/usr/xio_perftest/../../../../git/benchmarks/usr/xio_perftest/xio_msg.c:232: undefined reference to `free_mem_buf'

Signed-off-by: Arne Redlich <arne.redlich@openvstorage.com>